import 'package:travel_app/models/FlightsModel.dart';
import "package:flutter/material.dart";

List<FlightModel> flights = [
  FlightModel(
      airLine: "Ryanair",
      flightNumber: "EK202",
      departure: "DXB",
      destination: "JFK",
      departureTime: "10:00 am",
      arrivalTime: "4:00 pm",
      price: "1200",
      imageUrl: "images/ryanAir.png",
      color: Colors.white60,
      headerImage:
          "https://i.pinimg.com/originals/36/3d/bf/363dbf0ffa49288be404eb9beffa7264.jpg",
      startCountry: 'Dubai',
      endCountry: 'America',
      earlyPercentage: 0.5,
      onTimePercentage: 0.8,
      latePercentage: 0.2,
      cancelledPercentage: 0),
  FlightModel(
      airLine: "Easy Jet",
      flightNumber: "EK202",
      departure: "LGW",
      destination: "BER",
      departureTime: "10:00 am",
      arrivalTime: "4:00 pm",
      price: "1200",
      imageUrl: "images/easyjet.png",
      color: Colors.deepOrange,
      headerImage:
          "https://dnamediastorageprod.blob.core.windows.net/workshop/noclient/noworkshop/29006/31906/Logo_screen_full_hd.jpg",
      startCountry: 'London',
      endCountry: 'Berlin',
      earlyPercentage: 0.5,
      onTimePercentage: 0.8,
      latePercentage: 0.2,
      cancelledPercentage: 0),
  FlightModel(
      airLine: "British Airways",
      flightNumber: "EK202",
      departure: "LHR",
      destination: "NYC",
      departureTime: "10:00 am",
      arrivalTime: "4:00 pm",
      price: "1200",
      imageUrl: "images/BritishAirways.png",
      color: const Color(0xff0135AD),
      headerImage:
          "https://www.logodesignlove.com/wp-content/uploads/2013/01/ba-logo-white-on-blue-01.jpg",
      startCountry: 'London',
      endCountry: "New York",
      earlyPercentage: 0.5,
      onTimePercentage: 0.8,
      latePercentage: 0.2,
      cancelledPercentage: 0),
  FlightModel(
      airLine: "Wizz Air",
      flightNumber: "EK202",
      departure: "STN",
      destination: "VIE",
      departureTime: "10:00 am",
      arrivalTime: "4:00 pm",
      price: "1200",
      imageUrl: "images/wizzAir.png",
      color: Colors.black,
      headerImage:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Wizz_Air_Logo.png/1280px-Wizz_Air_Logo.png",
      startCountry: 'London',
      endCountry: 'Vienna',
      earlyPercentage: 0.5,
      onTimePercentage: 0.8,
      latePercentage: 0.2,
      cancelledPercentage: 0),
];
